apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.app.name}}
  name: {{.Values.app.name}}
  namespace: default
spec:
  minReadySeconds: 45
  replicas: {{.Values.app.replicas}}
  selector:
    matchLabels:
      app: {{.Values.app.name}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{.Values.app.name}}
    spec:
      containers:
        - image: {{.Values.app.image}}
          imagePullPolicy: Always
          name: {{.Values.app.name}}
          ports:
            - containerPort: {{.Values.app.port}}
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 400m
              memory: 1024Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.app.name}}-service
  name: {{.Values.app.name}}-service
  namespace: default
spec:
  type: {{.Values.service.servicetype}}
  ports:
    - port: {{.Values.app.port}}
      targetPort: {{.Values.app.port}}
      protocol: TCP
  selector:
    app: {{.Values.app.name}}
  sessionAffinity: None